import type { JsonObject } from '../../util/json';
import { SORT_KEYS } from './catalog';

/**
 * Documented defaults (notes §2–§4) for the files the codec writes, in the
 * key order MagicChatbox itself uses. Metadata keys are added on serialize.
 */

export const OSC_DEFAULTS: JsonObject = {
  OscIP: '127.0.0.1',
  OscPortOut: 9000,
  SecOSC: false,
  SecOSCIP: '127.0.0.1',
  SecOSCPort: 9002,
  ThirdOSC: false,
  ThirdOSCIP: '127.0.0.1',
  ThirdOSCPort: 9003,
  UnmuteMainOutput: true,
  UnmuteSecOutput: false,
  UnmuteThirdOutput: false,
};

const SETTINGS_TABS = [
  'Status',
  'OpenAI',
  'HeartRate',
  'Time',
  'Weather',
  'Twitch',
  'TikTokLive',
  'Discord',
  'Spotify',
  'ComponentStats',
  'NetworkStatistics',
  'Chatting',
  'TTS',
  'MediaLink',
  'AppOptions',
  'WindowActivity',
  'VrcRadar',
  'TrackerBattery',
  'VrPerformance',
  'Lyrics',
  'Voicemod',
  'Privacy',
];

export const APP_DEFAULTS: JsonObject = {
  ScanningInterval: 1.0,
  ScanPauseTimeout: 15,
  PrefixIconStatus: true,
  PrefixIconMusic: true,
  PrefixIconSoundpad: true,
  EmojiCollection: [],
  EnableEmojiShuffleInChats: false,
  EnableEmojiShuffle: false,
  OscMessagePrefix: '',
  OscMessageSeparator: ' ┆ ',
  OscMessageSuffix: '',
  SeperateWithENTERS: true,
  StartWithSteamVr: false,
  QuitWithSteamVr: false,
  SteamVrManifestPath: '',
  CountOculusSystemAsVR: true,
  Topmost: false,
  StableUpdateMode: 2,
  PreReleaseUpdateMode: 0,
  CheckUpdateOnStartup: true,
  StartInBackground: false,
  MinimizeToTray: false,
  CloseToTray: false,
  MinimizeToTrayOnMinimize: false,
  EnableTrayNotifications: true,
  ShowTrayRunningReminder: true,
  OpenTrayWithAltX: true,
  ShowHiddenIntegrationWarning: true,
  SwitchStatusInterval: 5,
  EggPrefixIconStatus: '🥚',
  IsRandomCycling: false,
  CycleStatus: false,
  CycleOverrideCurrentGroup: false,
  CycleOverrideGroupId: '',
  LastSelectedGroupId: '',
  BlankEgg: false,
  StatusRoundCorners: true,
  CurrentMenuItem: 0,
  PageScrollOffsets: {},
  OptionsSectionHeights: {},
  ...Object.fromEntries(SETTINGS_TABS.map((tab) => [`Settings_${tab}`, false])),
  WindowLeft: 'NaN',
  WindowTop: 'NaN',
  WindowWidth: 'NaN',
  WindowHeight: 'NaN',
  WindowMaximized: false,
  SettingsDev: false,
  AvatarSyncExecute: true,
  AppOpacity: 0.98,
  AppIsEnabled: true,
  ReducedVisuals: false,
  ReducedVisualsInVr: true,
  AcceptedTosVersion: '',
};

export const INTEGRATION_DEFAULTS: JsonObject = {
  IntgrStatus: true,
  IntgrScanWindowActivity: false,
  IntgrScanSpotify_OLD: false,
  IntgrScanWindowTime: true,
  ApplicationHookV2: true,
  IntgrHeartRate: false,
  IntgrNetworkStatistics: false,
  IntgrScanMediaLink: true,
  IntgrComponentStats: false,
  IntgrSoundpad: false,
  IntgrVoicemod: false,
  IntgrTwitch: false,
  IntgrTikTokLive: false,
  IntgrDiscord: false,
  IntgrSpotify: false,
  IntgrVrcRadar: false,
  IntgrTrackerBattery: false,
  IntgrVrPerformance: false,
  IntgrLyrics: false,
  IntgrLyrics_Spotify: false,
  IntgrLyrics_MediaLink: false,
  IntgrLyrics_VR: true,
  IntgrLyrics_DESKTOP: true,
  IntgrComponentStats_VR: true,
  IntgrComponentStats_DESKTOP: false,
  IntgrNetworkStatistics_VR: false,
  IntgrNetworkStatistics_DESKTOP: true,
  IntgrStatus_VR: true,
  IntgrStatus_DESKTOP: true,
  IntgrMediaLink_VR: true,
  IntgrMediaLink_DESKTOP: true,
  IntgrWindowActivity_VR: false,
  IntgrWindowActivity_DESKTOP: true,
  IntgrHeartRate_VR: true,
  IntgrHeartRate_DESKTOP: false,
  IntgrHeartRate_OSC: false,
  IntgrCurrentTime_VR: true,
  IntgrCurrentTime_DESKTOP: false,
  IntgrWeather_VR: true,
  IntgrWeather_DESKTOP: false,
  IntgrSpotifyStatus_VR: true,
  IntgrSpotifyStatus_DESKTOP: true,
  IntgrSoundpad_VR: false,
  IntgrSoundpad_DESKTOP: true,
  IntgrVoicemod_VR: true,
  IntgrVoicemod_DESKTOP: true,
  IntgrTwitch_VR: true,
  IntgrTwitch_DESKTOP: true,
  IntgrTikTokLive_VR: true,
  IntgrTikTokLive_DESKTOP: true,
  IntgrDiscord_VR: true,
  IntgrDiscord_DESKTOP: true,
  IntgrSpotify_VR: true,
  IntgrSpotify_DESKTOP: true,
  IntgrVrcRadar_VR: true,
  IntgrVrcRadar_DESKTOP: true,
  SavedSortOrder: [...SORT_KEYS],
  HiddenTiles: [],
  TileHideHintShown: false,
  HiddenStripCollapsed: false,
};

export const AFK_DEFAULTS: JsonObject = {
  AfkTimeout: 120,
  EnableAfkDetection: true,
  UseSmallLettersForDuration: true,
  ShowPrefixIcon: true,
  AfkPrefix: '💤',
  ActivateInVR: false,
  ShowAFKTime: true,
  AfkMessageForTimeStamp: 'ᶜᵘʳʳᵉⁿᵗˡʸ AFK ᶠᵒʳ ',
  AfkMessageWithoutTimeStamp: 'ᶜᵘʳʳᵉⁿᵗˡʸ AFK',
  OverrideAfk: false,
  CustomStyles: [],
  ActiveStyleId: '',
};

export const TIME_DEFAULTS: JsonObject = {
  Time24H: false,
  PrefixTime: false,
  TimeShowTimeZone: false,
  SelectedTimeZone: 0,
  UseDaylightSavingTime: true,
  UseSystemCulture: false,
  BussyBoysDate: '0001-01-01T00:00:00',
  BussyBoysDateEnable: false,
  BussyBoysMultiMODE: false,
};

export const MEDIALINK_DEFAULTS: JsonObject = {
  ShowOnlyOnChange: false,
  IconPlay: '',
  IconPause: '⏸',
  IconStop: '⏹️',
  ShowStopIcon: true,
  Separator: ' ᵇʸ ',
  TextPlaying: 'Listening to',
  TextPaused: 'Paused',
  UpperCase: false,
  PauseIconMusic: true,
  TimeSeekStyle: 0,
  AutoDowngradeSeekbar: true,
  ShortenToFit: true,
  TidyTitles: true,
  AutoSwitch: true,
  AutoSwitchSpawn: true,
  SessionTimeout: 3,
  Disabled: false,
  TransientDuration: 25.0,
};

export const SPOTIFY_DEFAULTS: JsonObject = {
  ClientId: '',
  AccessTokenEncrypted: '',
  RefreshTokenEncrypted: '',
  TokenExpiresAtUtcTicks: 0,
  AutoConnectOnStartup: true,
  PollingIntervalSeconds: 5,
  IdlePollingIntervalSeconds: 30,
  PauseOutputMode: 1,
  MediaLinkCoexistence: 0,
  WidgetMode: 1,
  ShowWidgetProgress: true,
  ShowWidgetDevice: true,
  ShowWidgetControls: true,
  ShowWidgetVolume: true,
  AllowTrackTitleInOutput: true,
  AllowArtistInOutput: true,
  AllowAlbumInOutput: true,
  AllowDeviceInOutput: true,
  AllowVolumeInOutput: true,
  AllowPlaybackStateInOutput: true,
  PrivacyChoicesCompleted: false,
  PrivacyMode: false,
  ShowTitle: true,
  ShowArtist: true,
  ShowAlbum: false,
  ShowDevice: false,
  ShowVolume: true,
  ShowProgress: false,
  ProgressDisplayMode: 2,
  AutoDowngradeProgress: true,
  ProgressBarLength: 8,
  ProgressShowTime: true,
  ProgressShowTimeInSuperscript: true,
  ProgressBarOnTop: false,
  ProgressSpaceAroundObjects: true,
  ProgressSpaceBetweenPreSuffixAndTime: false,
  ProgressTimePreSuffixOnTheInside: true,
  ProgressFilledCharacter: '▒',
  ProgressMiddleCharacter: '▓',
  ProgressNonFilledCharacter: '░',
  ProgressTimePrefix: '',
  ProgressTimeSuffix: '',
  SelectedSeekbarStyleId: 1,
  ShowExplicit: true,
  ShowLiked: true,
  ShowShuffle: true,
  ShowRepeat: true,
  PartyModeEnabled: true,
  ShowOnlyOnChange: false,
  TransientDuration: 25.0,
  OutputTemplate: '{play_icon} {artist} - {title} {liked_icon} {explicit_icon}',
  PartyTemplate: '{play_icon} DJ: {title} - {artist} {queue}',
  DisconnectedText: 'Spotify: connect account',
  EmptyText: 'Spotify: nothing playing',
  PausedText: 'Spotify paused',
  PrivacyHiddenText: 'Hidden',
  IconPlaying: '▶',
  IconPaused: '⏸',
  IconExplicit: '🅴',
  IconLiked: '♥',
  IconUnliked: '♡',
  IconShuffleOn: '🔀',
  IconShuffleOff: '',
  IconRepeatOff: '',
  IconRepeatContext: '🔁',
  IconRepeatTrack: '🔂',
  Separator: ' - ',
};

export const COMPONENT_STATS_DEFAULTS: JsonObject = {
  SelectedGPU: '',
  AutoSelectGPU: true,
  UseEmojisForTempAndPower: false,
  GPU3DHook: false,
  GPU3DVRAMHook: false,
  EnableVendorGpuSensors: true,
  ShowGpuFanSpeed: false,
  ShowGpuCoreClock: false,
  ShowGpuMemoryClock: false,
  ShowGpuMemoryTemperature: false,
  ShowGpuMemoryLoad: false,
  StatsSeparator: ' ¦ ',
  TemperatureCelsius: true,
  TemperatureFahrenheit: true,
  TemperatureKelvin: false,
  TemperatureRankine: false,
  TemperatureReaumur: false,
  TemperatureCompanionScale: 0,
  TemperatureDisplaySwitchInterval: 5,
  IsFahrenheit: false,
  IsTemperatureSwitchEnabled: true,
};

export interface ComponentSpec {
  readonly name: 'CPU' | 'GPU' | 'RAM' | 'VRAM';
  readonly smallName: string;
  readonly type: number;
  readonly unit: string;
  readonly showWattage: boolean;
  readonly removeTrailing: boolean;
  readonly showMax: boolean;
}

/** `SupportedComponentTypes` order: CPU, GPU, RAM, VRAM. */
export const COMPONENTS: readonly ComponentSpec[] = [
  {
    name: 'CPU',
    smallName: 'ᶜᵖᵘ',
    type: 1,
    unit: '﹪',
    showWattage: false,
    removeTrailing: true,
    showMax: false,
  },
  {
    name: 'GPU',
    smallName: 'ᵍᵖᵘ',
    type: 0,
    unit: '﹪',
    showWattage: true,
    removeTrailing: true,
    showMax: false,
  },
  {
    name: 'RAM',
    smallName: 'ʳᵃᵐ',
    type: 2,
    unit: 'ᵍᵇ',
    showWattage: false,
    removeTrailing: false,
    showMax: true,
  },
  {
    name: 'VRAM',
    smallName: 'ᵛʳᵃᵐ',
    type: 3,
    unit: 'ᵍᵇ',
    showWattage: false,
    removeTrailing: false,
    showMax: true,
  },
];

export function componentItemDefaults(spec: ComponentSpec, startedOn: string): JsonObject {
  return {
    StartedOn: startedOn,
    LastUpdated: '0001-01-01T00:00:00',
    SystemMainName: spec.name,
    SystemMailSmallName: spec.smallName,
    HardwareFriendlyName: null,
    HardwareFriendlyNameSmall: null,
    ShowPrefixHardwareTitle: false,
    ReplaceWithHardwareName: false,
    CustomHardwarenameValue: null,
    CustomHardwarenameValueSmall: null,
    ComponentType: spec.type,
    Unit: spec.unit,
    ShowTemperature: false,
    ShowHotSpotTemperature: false,
    cantShowTemperature: false,
    cantShowHotSpotTemperature: false,
    cantShowWattage: false,
    ShowWattage: spec.showWattage,
    ShowUnit: true,
    ComponentValue: '',
    ComponentValueMax: '',
    Available: true,
    RemoveNumberTrailing: spec.removeTrailing,
    ShowMaxValue: spec.showMax,
    IsEnabled: true,
    ShowSmallName: true,
    ShowDDRVersion: true,
    DDRVersion: null,
  };
}
