import type { JsonObject } from '../../util/json';
import { FILES } from './catalog';
import {
  AFK_DEFAULTS,
  APP_DEFAULTS,
  COMPONENT_STATS_DEFAULTS,
  INTEGRATION_DEFAULTS,
  MEDIALINK_DEFAULTS,
  OSC_DEFAULTS,
  SPOTIFY_DEFAULTS,
  TIME_DEFAULTS,
} from './defaults';

/** Documented defaults (notes §2.13–§2.21) for the remaining provider files. */

export const PULSOID_DEFAULTS: JsonObject = {
  ApplyHeartRateAdjustment: false,
  ThrottleHR: false,
  ThrottleMaxAdditional: 10,
  ThrottleHRMax: 105,
  CurrentHeartRateTitle: 'Heart Rate',
  DisableLegacySupport: false,
  EnableHeartRateOfflineCheck: true,
  HeartIcons: ['❤️', '💖', '💗', '💙', '💚', '💛', '💜'],
  HeartRateAdjustment: -5,
  HeartRateScanInterval: 1,
  HeartRateTitle: false,
  HeartRateTrendIndicatorSampleRate: 4,
  HeartRateTrendIndicatorSensitivity: 0.65,
  HideCurrentHeartRate: false,
  HighHeartRateText: 'hot',
  HighTemperatureThreshold: 100,
  LowHeartRateText: 'sleepy',
  LowTemperatureThreshold: 60,
  MagicHeartIconPrefix: true,
  MagicHeartRateIcons: true,
  PulsoidStatsEnabled: true,
  PulsoidTrendSymbols: [],
  SelectedPulsoidTrendSymbol: { DownwardTrendSymbol: '↓', UpwardTrendSymbol: '↑' },
  SelectedStatisticsTimeRange: 0,
  SentMCBHeartrateInfo: false,
  SentMCBHeartrateInfoLegacy: false,
  SeparateTitleWithEnter: false,
  ShowAverageHeartRate: true,
  ShowBPMSuffix: false,
  ShowCalories: false,
  ShowDuration: false,
  ShowHeartRateTrendIndicator: true,
  ShowMaximumHeartRate: true,
  ShowMinimumHeartRate: true,
  ShowStatsTimeRange: false,
  ShowTemperatureText: true,
  SmoothHeartRate: true,
  SmoothHeartRateTimeSpan: 4,
  SmoothOSCHeartRate: true,
  SmoothOSCHeartRateTimeSpan: 4,
  StatisticsTimeRanges: [],
  TrendIndicatorBehindStats: true,
  UnchangedHeartRateTimeoutInSec: 30,
  AccessTokenOAuthEncrypted: '',
};

export const WEATHER_DEFAULTS: JsonObject = {
  ShowWeatherInTime: true,
  ShowWeatherCondition: false,
  ShowWeatherEmoji: false,
  WeatherUseDecimal: false,
  ShowWeatherHumidity: false,
  ShowWeatherWind: false,
  ShowWeatherFeelsLike: false,
  WeatherSeparator: ' | ',
  WeatherStatsSeparator: ' ',
  WeatherConditionOverrides: '',
  WeatherCustomOverridesEnabled: false,
  WeatherLayoutMode: 0,
  WeatherOrder: 0,
  WeatherUnitOverride: 0,
  WeatherCompanionScale: 0,
  WeatherWindUnitOverride: 0,
  WeatherFallbackMode: 0,
  WeatherLocationMode: 0,
  WeatherAllowIPLocation: false,
  WeatherLocationEditing: false,
  WeatherLocationLatitude: 0,
  WeatherLocationLongitude: 0,
  WeatherUpdateIntervalMinutes: 10,
  WeatherTemplate: '',
  WeatherLocationCityEncrypted: '',
};

export const NETWORK_DEFAULTS: JsonObject = {
  ShowCurrentDown: true,
  ShowCurrentUp: false,
  ShowMaxDown: false,
  ShowMaxUp: false,
  ShowTotalDown: false,
  ShowTotalUp: false,
  ShowNetworkUtilization: true,
  UseInterfaceMaxSpeed: false,
  StyledCharacters: true,
};

export const WINDOW_DEFAULTS: JsonObject = {
  AutoShowTitleOnNewApp: false,
  TitleScan: true,
  MaxShowTitleCount: 35,
  LimitTitleOnApp: true,
  TitleOnAppVR: false,
  PrivateName: '🔒 App',
  PrivateNameVR: '🔒 App',
  HideOutputWhenPrivateApp: false,
  VrTitle: 'In VR',
  VrFocusTitle: 'ᶠᵒᶜᵘˢˢⁱⁿᵍ ⁱⁿ',
  DesktopTitle: 'On desktop',
  DesktopFocusTitle: 'ⁱⁿ',
  ShowFocusedApp: true,
  ApplicationHookV2: true,
  ShowRegexColumn: false,
  UseGlobalRegex: true,
  GlobalRegex: '^(.+?)(?:\\s*[-–—]\\s*[^-–—]+\\s*[-–—]\\s*(.+)|\\s*[-–—]\\s*[^-–—]+)?$ => $1 $2',
  EnableTitleFilters: false,
  TitleFilters: [],
};

export const VRC_LOG_DEFAULTS: JsonObject = {
  DisplayMode: 2,
  AnnounceJoins: true,
  AnnounceLeaves: true,
  AnnounceScreenshots: true,
  ShowInstanceType: true,
  ShowRegion: true,
  ShowWorldDownload: true,
  DetectSeenAgain: false,
  SeenAgainWindowMinutes: 5,
  ShowSessionStatsInChatbox: false,
  ShowSeenAgainNotification: true,
  WarnOnAvatarBlocked: true,
  UseWindowDetection: true,
  SessionTimeoutMinutes: 15,
  ShowEncounterTable: false,
  MinEncounterCount: 2,
  TemplateWorld: '{master}🌎 {world} | 👥 {count} | {type} {region}',
  TemplateJoin: '👋 {user} joined!',
  TemplateLeave: '🏃 {user} left',
  TemplateScreenshot: '📸 *Click!* Just took a picture!',
  TemplateDownload: '⏳ Loading world... {size}MB @ {speed}MB/s',
  TemplateSeenAgain: '👀 {user} is here again!',
  TemplateSessionStats: '📊 {worlds} worlds | {players} players met | Peak: {peak_session}',
  TemplateAvatarBlocked: '⚠️ Avatar blocked by performance shield',
  MasterIcon: '👑 ',
  JoinLeaveDuration: 4,
  ScreenshotDuration: 4,
  DownloadDuration: 8,
  SeenAgainDuration: 5,
  SessionStatsDuration: 15,
  AvatarBlockedDuration: 6,
  SendCameraFlashOsc: false,
  OscCameraFlashParam: '/avatar/parameters/CameraFlash',
  MaxBackfillSizeMb: 10,
};

export const TRACKER_BATTERY_DEFAULTS: JsonObject = {
  Template: '{icon} {name} {batt}%',
  Prefix: '',
  Suffix: '',
  Separator: ' | ',
  GlobalEmergency: false,
  ShowControllers: true,
  ShowHeadset: true,
  ShowTrackers: false,
  ShowDisconnected: false,
  OfflineBatteryText: 'N/A',
  OnlineText: 'Online',
  OfflineText: 'Offline',
  LowTag: 'LOW',
  CompactWhitespace: true,
  UseSmallText: false,
  SortMode: 0,
  RotateOverflow: false,
  LowThreshold: 20,
  MaxEntries: 2,
  RotationIntervalSeconds: 5,
  MaxEntryLength: 0,
  SavedDevices: [],
};

export const VR_PERFORMANCE_DEFAULTS: JsonObject = {
  ShowFps: true,
  ShowTargetHz: false,
  ShowReprojection: true,
  ShowDroppedFrames: false,
  ShowMotionSmoothing: false,
  ShowAppGpuMs: false,
  ShowCompositorGpuMs: false,
  ShowHeadroom: false,
  ShowCpuTiming: false,
  UseEmojisForVrPerf: true,
  UseSuperscriptUnits: true,
  StatsSeparator: ' ¦ ',
  RemoveNumberTrailing: false,
  DisplayMode: 0,
  DegradedReprojectionPercent: 10,
  DegradedDroppedPerMinute: 5,
  DegradedFpsPercentOfTarget: 90,
  DegradedHysteresisSeconds: 5,
};

export const TWITCH_DEFAULTS: JsonObject = {
  ChannelName: '',
  ClientIdEditing: false,
  AccessTokenEditing: false,
  ShowViewerCount: true,
  ShowGameName: true,
  ShowLiveIndicator: true,
  LivePrefix: 'LIVE',
  OfflineMessage: '',
  ShowStreamTitle: false,
  StreamTitlePrefix: 'title',
  ShowChannelName: false,
  ChannelPrefix: 'channel',
  GamePrefix: 'playing',
  ShowViewerLabel: true,
  ViewerLabel: 'viewers',
  ViewerCountCompact: false,
  ShowFollowerCount: false,
  ShowFollowerLabel: true,
  FollowerLabel: 'followers',
  FollowerCountCompact: false,
  UseSmallText: true,
  Separator: ' | ',
  Template: '',
  UpdateIntervalSeconds: 60,
  AnnouncementsEnabled: false,
  AnnouncementMessage: '',
  AnnouncementColor: 0,
  ShoutoutsEnabled: false,
  ShoutoutTarget: '',
  ShoutoutAlsoAnnounce: true,
  ShoutoutAnnouncementTemplate: 'Go follow {user} at twitch.tv/{user}',
  ShoutoutAnnouncementColor: 4,
  ClientIdEncrypted: '',
  AccessTokenEncrypted: '',
};

export const TIKTOK_DEFAULTS: JsonObject = {
  ProfileUserName: '',
  ShowProfileSummary: true,
  ProfileTemplate: 'TikTok @{profile} | {followers} followers',
  ProfileRefreshMinutes: 30,
  ShowProfileFollowerChangeEvents: true,
  ProfileFollowerChangeTemplate: 'TikTok +{change} followers | {followers} total',
  ProfileFollowerChangeDurationSeconds: 8,
  HostUserName: '',
  EnableLiveConnector: false,
  ExperimentalEnabled: false,
  AutoConnectOnStartup: true,
  DisplayMode: 1,
  CombineProfileAndLive: true,
  OutputOrder: 0,
  CombinedOutputSeparator: ' | ',
  CompactViewerCount: true,
  CompactLikeCount: true,
  SummaryTemplate: 'LIVE @{host} | {viewers} viewers | {likes} likes',
  ShowFollowEvents: true,
  ShowCommentEvents: false,
  ShowGiftEvents: true,
  ShowLikeEvents: false,
  ShowViewerMilestones: false,
  FollowTemplate: '➕ {user} followed',
  CommentTemplate: '💬 {user}: {message}',
  GiftTemplate: '🎁 {user} sent {gift} x{count}',
  LikeTemplate: '❤️ {user} +{count} likes',
  ViewerMilestoneTemplate: '👀 {viewers} viewers',
  EventDurationSeconds: 6,
  ViewerMilestoneDurationSeconds: 4,
  LikeBurstThreshold: 25,
  ViewerCountMilestoneStep: 100,
  ReconnectDelaySeconds: 6,
  ConnectionTimeoutSeconds: 15,
};

export const DISCORD_DEFAULTS: JsonObject = {
  Template: '🔊 {channel} ({count}) | 🎙️ {speaking}',
  EmptySpeakingText: 'Quiet...',
  NotInVcText: '',
  MaxSpeakingUsersToShow: 2,
  ShowMuteDeafenEmoji: true,
  MuteEmoji: 'ᵐᵘᵗᵉᵈ',
  DeafenEmoji: 'ᵈᵉᵃᶠᵉⁿ',
  AutoConnectOnStartup: false,
  HideSelfFromSpeakers: false,
  ShowUserCountOnly: false,
  SpeakerDebounceMs: 500,
  SendMuteDeafenOsc: false,
  SendVoiceStateOsc: false,
  EnableRichPresence: false,
  RichPresenceDetails: 'In {world}',
  RichPresenceState: '{count} players • {type}',
  RichPresenceShowJoinButton: false,
  RichPresenceLargeText: 'VRChat',
  RichPresenceLargeImageKey: 'vrchat_logo',
  RichPresenceSmallImageKey: 'magicchatbox',
  RichPresenceSmallText: 'MagicChatbox',
  RichPresenceShowElapsed: true,
  RichPresenceShowVrDesktopMode: true,
  RichPresenceJoinButtonLabel: 'Join World',
  VoiceClientIdEncrypted: '',
  TokenExpiresAtUtcTicks: 0,
  HasRpcScope: true,
  AccessTokenEncrypted: '',
  RefreshTokenEncrypted: '',
};

export const LYRICS_DEFAULTS: JsonObject = {
  OffsetMs: 0,
  ShowNoteIcon: true,
  ShowGapMarker: true,
  MinimumCharacters: 24,
  Coexistence: 1,
  GapThresholdSeconds: 8,
  LineHoldSeconds: 6,
  UseLocalFiles: true,
  LocalLyricsFolder: '',
  InstrumentalMarker: 3,
  SuperscriptAsides: true,
  MatchStrictness: 1,
  BroadenSearchWhenNoMatch: true,
};

/** Defaults for every settings file the codec always emits (StatusList and ComponentStatsV1 are built separately). */
export const FILE_DEFAULTS: Readonly<Record<string, JsonObject>> = {
  [FILES.app]: APP_DEFAULTS,
  [FILES.osc]: OSC_DEFAULTS,
  [FILES.integration]: INTEGRATION_DEFAULTS,
  [FILES.afk]: AFK_DEFAULTS,
  [FILES.time]: TIME_DEFAULTS,
  [FILES.mediaLink]: MEDIALINK_DEFAULTS,
  [FILES.spotify]: SPOTIFY_DEFAULTS,
  [FILES.componentStats]: COMPONENT_STATS_DEFAULTS,
  [FILES.pulsoid]: PULSOID_DEFAULTS,
  [FILES.weather]: WEATHER_DEFAULTS,
  [FILES.network]: NETWORK_DEFAULTS,
  [FILES.window]: WINDOW_DEFAULTS,
  [FILES.vrcLog]: VRC_LOG_DEFAULTS,
  [FILES.trackerBattery]: TRACKER_BATTERY_DEFAULTS,
  [FILES.vrPerformance]: VR_PERFORMANCE_DEFAULTS,
  [FILES.twitch]: TWITCH_DEFAULTS,
  [FILES.tiktok]: TIKTOK_DEFAULTS,
  [FILES.discord]: DISCORD_DEFAULTS,
  [FILES.lyrics]: LYRICS_DEFAULTS,
};

/** Files that carry `_schemaVersion` / `_appVersion` / `_migratedAt`. */
export const VERSIONED_FILES: readonly string[] = Object.keys(FILE_DEFAULTS).filter(
  (name) => name !== FILES.afk,
);
